module.exports.club = [
'Gym',
'Up',
'Strength',
'Zone',
'Athletes',
'Bar',
'Palace',
'Gym',
'Zone',
'House',
'Fitness',
'Fitness',
'Gym',
'Center',
'Gym',
'Fitness',
'Factory',
'Body Techs',
'Fitness Center',
'Power Factory',
'Studio Gym',
'Gym',
'Fitness Plus',
'Studio Fixx',
'Gym',
'Strong',
'Behaviour',
'Strength',
'as One',
'Gym',
'Gym',
'Fitness Center',
'Health Club',
'Balance Club',
'Gym',
'Training Centre',
'Fitness Centre',
'Fit Gym',
'Fitness Club',
'Fitness Club',
'Gym',
'Gym',
'Gym',
'Health Club',
'Fitness Centre',
'Fitness Club'
]

module.exports.description = [
    
    'Heroes',
    'PumpIt',
    'Center of',
    'Power',
    'Home of Fit',
    'The Muscle',
    'Strength',
    'Total Body',
    'Energy',
    'Pump',
    'Kick it',
    'Airdyne',
    'Vertical Athlete',
    'Bands Workout',
    'Mettle Fitness',
    'Engage',
    'Fit Factory',
    'KMGF Body',
    'Anytime Fitness',
    'Power Factory',
    'Power House',
    '24/7 Workout',
    'Anytime Fitness',
    'Power Train',
    'Studio Fixx',
    'The Shapes',
    'Alternative Thinking',
    'Be Strong',
    'The Fit Behaviour',
    'Full Strength',
    'Work out as One',
    'Power, Strength, and Fitness',
    'The',
    'Ajax',
    'Alma',
    'Arctic',
    'Artistic Balance',
    'Aspire',
    'Backhand Sports',
    'Banedan',
    'Basic Fit',
    'Best Body',
    'Bethune',
    'Rock Hard',
    'Golden Gorilla',
    'Fight Cluub',
    'Iron Will',
    'Health'
    ]